# Generated by Django 4.1.5 on 2023-01-13 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 15, 9, 28, 484086)),
        ),
    ]
