# Generated by Django 4.1.5 on 2023-01-17 04:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 10, 2, 50, 705536)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('commented_date', models.DateTimeField(default=datetime.datetime(2023, 1, 17, 10, 2, 50, 705865))),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogs')),
            ],
        ),
    ]
