# Generated by Django 4.1.5 on 2023-07-09 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_commented_date_rename_authors_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 13, 45, 49, 157429)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 13, 45, 49, 157429)),
        ),
    ]
